### ISSUE TITLE
Split payment

### ISSUE THREAD

**Issue by artmedia** [FatturaElettronicaPA/FatturaElettronicaPA#1]
Nicola,
per il campo <EsigibilitaIVA> va aggiunto il valore "S" tra quelli ammissibili per lo Split Payment
http://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-2.htm
Inoltre, nel caso dello split payment, il campo <ImportoPagamento> dovrebbe essere al netto dell'iva (uso il condizionale perche' questo non è ancora stato ufficializzato)
PS: ottimo lavoro la F.E. open source, la usero' nel mio gestionale online ioFatturo.it

**Comment by artmedia** [comment]
(ops.. ci riprovo senza mettere il carattere maggiore/minore per identificare i campi)

Nicola,
per il campo "EsigibilitaIVA" va aggiunto il valore "S" tra quelli ammissibili per lo Split Payment
http://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-2.htm
Inoltre, nel caso dello split payment, il campo "ImportoPagamento" dovrebbe essere al netto dell'iva (uso il condizionale perche' questo non è ancora stato ufficializzato)
PS: ottimo lavoro la F.E. open source, la usero' nel mio gestionale online ioFatturo.it

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Ho rilasciato la v0.1.1 che aggiunge supporto per split payment.
