### ISSUE TITLE
DateTime nullable

### ISSUE THREAD

**Issue by sibylmichelangelotodaro** [FatturaElettronicaPA/FatturaElettronicaPA#10]
I campi DatiTrasporto.DataOraConsegna e DettaglioPagamento.DataScadensaPagamento, dovrebbero essere di tipo DateTime?, perchè non obbligatori, e quindi evitare di avere il campo valorizzato nel file xml con  il valore mindate.

**Comment by nicolaiarocci** [comment]
Grazie. Puoi testare se ora funziona per cortesia?

**Comment by sibylmichelangelotodaro** [comment]
Ciao. Confermo il corretto comportamento. Grazie
