### ISSUE TITLE
Errore nullable su campo GiorniTerminiPagamento (2.4.2.4)

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronicaPA/FatturaElettronicaPA#13]
Se specificato si ottine un errore del tipo
Content cannot be converted to the type System.Nullable`1[System.Int32]........

**Comment by gptucci** [comment]
Ecco un esempio
https://drive.google.com/file/d/0B3b3qgfFZg9CMnBzNElndlFYTUU/view?usp=sharing
Ritengo sia connesso a "Cannot convert to Nullable durante de-serializzazione "

Grz

**Comment by nicolaiarocci** [comment]
Dovrebbe essere risolto dalla v0.1.7

**Comment by gptucci** [comment]
E' perfetto
Grazie
