### ISSUE TITLE
Nuovo errore 00423

### ISSUE THREAD

**Issue by sibylmichelangelotodaro** [FatturaElettronicaPA/FatturaElettronicaPA#17]
Riguardo al nuovo errore 00423 ho chiesto chiarimenti all'assistenza del portale FatturaPA.
Tale errore viene segnalato sul seguente blocco:
```
<DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>SERIE CAVI CANDELA</Descrizione>
        <Quantita>1.00</Quantita>
        <PrezzoUnitario>48.65</PrezzoUnitario>
        <ScontoMaggiorazione>
                <Tipo>SC</Tipo>
                <Percentuale>33.42</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>32.39</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
</DettaglioLinee>
```

Il problema nasce dal fatto che viene effettuata una verifica sul valore PrezzoTotale senza considerare l'arrotondamento a 2 cifre.
Di seguito la regola:

IF ( PrezzoTotale != ( PrezzoUnitario - Sconto ) * Quantità )
    E R R O R E (00423)

ovvero, nel caso di sopra:

32.39 != 32.39117

Ecco la loro risposta:

Gentile Utente,
in merito alla Sua richiesta La informiamo che lo sconto maggiorazione (campo 2.2.1.10) previsto all'interno del blocco <dettaglio linee> deve essere sempre riferito al prezzo unitario (campo 2.2.1.9) e mai al prezzo totale (campo 2.2.1.11).
Per risolvere l'errore si può mettere il prezzo unitario per intero (senza aggiungere nello stesso blocco lo sonto/maggiorazione) e aggiungere una nuova linea di fattura con tipo cessione prestazione (campo 2.2.1.2 = SC (sconto), prezzo unitario espresso in negativo corrispondente al valore totale dello sconto e prezzo totale = prezzo unitario.
Lo  sconto si evidenzierà nel blocco dei dati di riepilogo (riferito all'aliquota corrispondente alla linea dello sconto) dove l'imponibile importo (2.2.2.5) sarà dato dal prezzo totale del bene - l'importo dello sconto.
La invitiamo, inoltre, a consultare la guida presente sul sito www.fatturapa.gov.it:
- Norme e Regole (sezione destra del portale)
- Prendere visione della guida (menù di sinistra) "Rappresentazione tabellare del tracciato della FatturaPA versione 1.1 pdf" e "Suggerimenti per la compilazione della FatturaPA versione 1.2".

Cordiali saluti,
 Servizio Assistenza

Che ne pensate?

**Comment by nicolaiarocci** [comment]
Fix implementata sia sul lato FatturaElettronicaPA che Amica (prossima release 2.12.02).

**Comment by nicolaiarocci** [comment]
E grazie per il prezioso report che ci ha aiutato a implementare un test efficace.

**Comment by sibylmichelangelotodaro** [comment]
Grazie a voi

**Comment by sibylmichelangelotodaro** [comment]
Aggiornamento sulla normativa:

"Il controllo recentemente introdotto sul calcolo del PrezzoTotale prevede una tolleranza che ne rende ‘accettabile’ l’arrotondamento alla seconda cifra decimale."

Non è quindi necessario implementare la soluzione che mi avevano proposto nel messaggio precedente.

**Comment by nicolaiarocci** [comment]
Sì, grazie. Sono tornati indietro: ora accettano i 2 decimali solamente ma con "compensazione" sull'arrotondamento. Apro ticket.

**Comment by nicolaiarocci** [comment]
Vedi #19
