### ISSUE TITLE
ERRORE Validazione 00423: calcolo in base a percentuale sconto

### ISSUE THREAD

**Issue by marcoantinori** [FatturaElettronicaPA/FatturaElettronicaPA#18]
Dall'elenco controlli V 1.2 Validazione Prezzo totale (errore 00423) pag. 25

> "In caso di presenza contemporanea di Importo e Percentuale, si considera solo il primo ai fini del calcolo"

Nel metodo `ValidateAgainstErr00423()` invece sembra essere prioritario il calcolo in base alla percentuale:

`	var importo = (decimal)((sconto.Percentuale == null) ? sconto.Importo : (PrezzoUnitario * sconto.Percentuale) / 100);`

Inoltre, nel calcolo dello sconto in base alla percentuale, sembra non valere la regola dello sconto a "cascata"

> "Se sono rappresentati come percentuale, il calcolo tiene conto dell’effetto ‘a cascata’ ; pertanto il valore totale è dato dalla somma dei valori
> di sconto/maggiorazione ottenuti applicando al prezzo unitario la percentuale secondo la regola che segue
> `( PrezzoUnitario * Percentuale ) ∕ 100`
> ma dove il PrezzoUnitario assume di volta in volta un valore più basso/più alto per effetto dell’applicazione dello sconto/maggiorazione
> precedentemente applicato/a."

ma il valore del `PrezzoUnitario `non viene decrementato di volta in volta degli sconti apportati

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Ora dovrebbe essere a posto. La 0.2.4 verrà rilasciata a breve.
