### ISSUE TITLE
Deserializzazione da XML

### ISSUE THREAD

**Issue by DiegoMartelli** [FatturaElettronicaPA/FatturaElettronicaPA#3]
Una volta serializzata una fattura elettronica in formato XML è impossibile deserializzarla nuovamente perché solleva un'eccezione sulla conversione dei tipi decimal?.

**Comment by nicolaiarocci** [comment]
Risolto in https://github.com/FatturaElettronicaPA/BusinessObjects/commit/5497f90532052a293797868679562ef83ffa0c12
