### ISSUE TITLE
 ContattiTrasmittente

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronicaPA/FatturaElettronicaPA#7]
Se nn specificato nel file xml si ha errore, 
Dalle specifiche è opzionale

**Comment by nicolaiarocci** [comment]
- Puoi allegare un xml col problema? 
- L'errore viene dato in fase di caricamento?

**Comment by gptucci** [comment]
Certo
Ecco qui

<?xml version="1.0" encoding="UTF-8"?>
<p:FatturaElettronica versione="1.1" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:p="http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <FatturaElettronicaHeader>
    <DatiTrasmissione>
      <IdTrasmittente>
        <IdPaese>IT</IdPaese>
        <IdCodice>01234567890</IdCodice>
      </IdTrasmittente>
      <ProgressivoInvio>AAA111</ProgressivoInvio>
      <FormatoTrasmissione>SDI11</FormatoTrasmissione>
      <CodiceDestinatario>021281</CodiceDestinatario>
      <ContattiTrasmittente/>
    </DatiTrasmissione>
    <CedentePrestatore>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>01234567890</IdCodice>
        </IdFiscaleIVA>
        <Anagrafica>
          <Denominazione>Studio Architettura</Denominazione>
        </Anagrafica>
        <RegimeFiscale>RF01</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>Indirizzo Mittente</Indirizzo>
        <CAP>01234</CAP>
        <Comune>Comune mittente</Comune>
        <Provincia>PR</Provincia>
        <Nazione>IT</Nazione>
      </Sede>
    </CedentePrestatore>
    <CessionarioCommittente>
      <DatiAnagrafici>
        <CodiceFiscale>ITCFINPSVEN</CodiceFiscale>
        <Anagrafica>
          <Denominazione>INPS</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>Indirizzo destinatario</Indirizzo>
        <CAP>56789</CAP>
        <Comune>Comune destinatario</Comune>
        <Provincia>PR</Provincia>
        <Nazione>IT</Nazione>
      </Sede>
    </CessionarioCommittente>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD01</TipoDocumento>
        <Divisa>EUR</Divisa>
        <Data>2014-12-18</Data>
        <Numero>FAT425630_01</Numero>
        <Causale>LA FATTURA FA RIFERIMENTO AD UNA OPERAZIONE AAAA BBBBBBBBBBBBBBBBBB CCC DDDDDDDDDDDDDDD E FFFFFFFFFFFFFFFFFFFF GGGGGGGGGG HHHHHHH II LLLLLLLLLLLLLLLLL MMM NNNNN OO PPPPPPPPPPP QQQQ RRRR SSSSSSSSSSSSSS</Causale>
        <Causale>SEGUE DESCRIZIONE CAUSALE NEL CASO IN CUI NON SIANO STATI SUFFICIENTI 200 CARATTERI AAAAAAAAAAA BBBBBBBBBBBBBBBBB</Causale>
      </DatiGeneraliDocumento>
      <DatiOrdineAcquisto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>0123456</IdDocumento>
        <NumItem>1</NumItem>
        <CodiceCUP>67E9E</CodiceCUP>
        <CodiceCIG>67E9E</CodiceCIG>
      </DatiOrdineAcquisto>
      <DatiContratto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>0123456</IdDocumento>
        <Data>2015-02-12</Data>
        <NumItem>5</NumItem>
        <CodiceCUP>67E9E</CodiceCUP>
        <CodiceCIG>67E9E</CodiceCIG>
      </DatiContratto>
      <DatiConvenzione>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>0123456</IdDocumento>
        <NumItem>5</NumItem>
        <CodiceCUP>67E9E</CodiceCUP>
        <CodiceCIG>67E9E</CodiceCIG>
      </DatiConvenzione>
      <DatiTrasporto>
        <DatiAnagraficiVettore>				
          <IdFiscaleIVA>
            <IdPaese>IT</IdPaese>
            <IdCodice>24681012141</IdCodice>
          </IdFiscaleIVA>
          <Anagrafica>
            <Denominazione>Trasporto spa</Denominazione>
          </Anagrafica>
        </DatiAnagraficiVettore>
        <DataOraConsegna>2012-10-22T16:46:12.000+02:00</DataOraConsegna>
      </DatiTrasporto>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>LA DESCRIZIONE DELLA FORNITURA PUO' SUPERARE I CENTO CARATTERI CHE RAPPRESENTAVANO IL PRECEDENTE LIMITE DIMENSIONALE. TALE LIMITE NELLA NUOVA VERSIONE E' STATO PORTATO A MILLE CARATTERI</Descrizione>
        <Quantita>5.00</Quantita>
        <PrezzoUnitario>1.00</PrezzoUnitario>
        <PrezzoTotale>5.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>FORNITURE VARIE PER UFFICIO</Descrizione>
        <Quantita>10.00</Quantita>
        <PrezzoUnitario>2.00</PrezzoUnitario>
        <PrezzoTotale>20.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <ImponibileImporto>27.00</ImponibileImporto>
        <Imposta>5.95</Imposta>
        <EsigibilitaIVA>I</EsigibilitaIVA>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>TP01</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP01</ModalitaPagamento>
        <DataScadenzaPagamento>2015-01-30</DataScadenzaPagamento>
        <ImportoPagamento>32.95</ImportoPagamento>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD01</TipoDocumento>
        <Divisa>EUR</Divisa>
        <Data>2014-12-20</Data>
        <Numero>FAT425630_02</Numero>
        <Causale>LA FATTURA FA RIFERIMENTO AD UNA OPERAZIONE AAAA BBBBBBBBBBBBBBBBBB CCC DDDDDDDDDDDDDDD E FFFFFFFFFFFFFFFFFFFF GGGGGGGGGG HHHHHHH II LLLLLLLLLLLLLLLLL MMM NNNNN OO PPPPPPPPPPP QQQQ RRRR SSSSSSSSSSSSSS</Causale>
        <Causale>SEGUE DESCRIZIONE CAUSALE NEL CASO IN CUI NON SIANO STATI SUFFICIENTI 200 CARATTERI AAAAAAAAAAA BBBBBBBBBBBBBBBBB</Causale>
      </DatiGeneraliDocumento>
      <DatiOrdineAcquisto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>66685</IdDocumento>
        <NumItem>1</NumItem>
        <CodiceCUP>123abc</CodiceCUP>
        <CodiceCIG>456def</CodiceCIG>
      </DatiOrdineAcquisto>
      <DatiContratto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>123</IdDocumento>
        <Data>2012-09-01</Data>
        <NumItem>5</NumItem>
        <CodiceCUP>123abc</CodiceCUP>
        <CodiceCIG>456def</CodiceCIG>
      </DatiContratto>
      <DatiConvenzione>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>321</IdDocumento>
        <NumItem>5</NumItem>
        <CodiceCUP>123abc</CodiceCUP>
        <CodiceCIG>456def</CodiceCIG>
      </DatiConvenzione>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>PRESTAZIONE DEL SEGUENTE SERVIZIO PROFESSIONALE: LA DESCRIZIONE DELLA PRESTAZIONE PUO' SUPERARE I CENTO CARATTERI CHE RAPPRESENTAVANO IL PRECEDENTE LIMITE DIMENSIONALE. TALE LIMITE NELLA NUOVA VERSIONE E' STATO PORTATO A MILLE CARATTERI</Descrizione>
        <PrezzoUnitario>2000.00</PrezzoUnitario>
        <PrezzoTotale>2000.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <ImponibileImporto>2000.00</ImponibileImporto>
        <Imposta>440.00</Imposta>
        <EsigibilitaIVA>I</EsigibilitaIVA>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>TP01</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP19</ModalitaPagamento>
        <DataScadenzaPagamento>2015-01-28</DataScadenzaPagamento>
        <ImportoPagamento>2440.00</ImportoPagamento>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
</p:FatturaElettronica>

**Comment by gptucci** [comment]
Grazie
Non me lo fa allegare, forse per mia imperizia
Te lo allego per mail
Scusami


Giampaolo Ing. TUCCI
3T Sistemi
Direzione Tecnica
Tel. (+39) 010 42064013
mail: assistenza@3tsistemi.it
web: www.3tsistemi.it

----- Original Message -----

**Comment by gptucci** [comment]
Certo
Ecco qui
https://drive.google.com/file/d/0B3b3qgfFZg9CdFNKSUhFOGJpQWc/view?usp=sharing
In questo caso il nodo è senza contenuto
<ContattiTrasmittente/>

Grazie
