### ISSUE TITLE
Causale - doppia riga

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronicaPA/FatturaElettronicaPA#8]
Se sono specificate 2 righe di causale (previsto dalla normativa) allora si ha un "loop" nel codice

**Comment by nicolaiarocci** [comment]
- Quale 'causale' ce ne sono diverse. Per favore fornire nome campo completo e possibilente il codice (es. 2.4.2.1)

**Comment by gptucci** [comment]
Grazie hai ragione
Scusami l'imprecisione
FatturaElettronicaBody - DatiGenerali - DatiGeneraliDocumento
2.1.1.11
