### ISSUE TITLE
Valore RiferimentoNumeroLinea

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronicaPA/FatturaElettronicaPA#9]
Se specificato si ha un errore conversione nullable

**Comment by nicolaiarocci** [comment]
- Quale anche di questi ce ne sono diversi: DDT, Ordine, ecc. Indicare il percorso completo oppure il numero di codice.

Ticket aperti con così poche indicazioni verrano chiusi automaticamente da ora in poi :)

**Comment by gptucci** [comment]
Mi arciscuso per l'imprecisione
FatturaElettronicaBody - DatiGenerali - DatiOrdineAcquisto
2.1.2.1

Grazie ancora e riscusatemi
